name: Deploy docs to Github Pages

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate static vuepress files
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run docs:build
      
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/.vuepress/dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'Deploy docs'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/.vuepress/dist

        


